# ARDUINO_DIR – Directory where Arduino is installed
ARDUINO_DIR=/mnt/data/bin/arduino_current

# ARDMK_DIR – Directory where you have copied the makefile
ARDMK_DIR=/mnt/data/repositories/arduino_thirdparty/Arduino-Makefile

CFLAGS_STD		+= -std=c11
CXXFLAGS_STD	+= -std=c++11

include ../../Arduino.mk
