CURRENT_OS=LINUX

# ARDUINO_DIR – Directory where Arduino is installed
ARDUINO_DIR=/mnt/data/bin/arduino-1.6.7

# ARDMK_DIR – Directory where you have copied the makefile
ARDMK_DIR=/mnt/data/repositories/arduino_thirdparty/Arduino-Makefile

# AVR_TOOLS_DIR – Directory where avr tools are installed
AVR_TOOLS_DIR=/usr

AVRDUDE_CONF=/usr/share/arduino/hardware/tools/avrdude.conf

include ../../Arduino.mk
